"""add brand settings

Revision ID: 2b49f5af03f3
Revises: b75c7618f104
Create Date: 2026-07-11 18:14:01.034513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b49f5af03f3'
down_revision: Union[str, Sequence[str], None] = 'b75c7618f104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Idempotent: app startup's create_all() may have created the table already
    on a deploy that raced this migration.
    """
    bind = op.get_bind()
    if "brand_settings" in sa.inspect(bind).get_table_names():
        return

    op.create_table('brand_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('accent_color', sa.String(), nullable=True),
    sa.Column('report_footer', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brand_settings')
    # ### end Alembic commands ###
