"""add report schedules

Revision ID: 47e49be32c49
Revises: 8a2fd618cc9f
Create Date: 2026-07-12 15:19:34.238480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e49be32c49'
down_revision: Union[str, Sequence[str], None] = '8a2fd618cc9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Idempotent: app startup's create_all() may have created the table already
    on a deploy that raced this migration.
    """
    bind = op.get_bind()
    if "report_schedules" in sa.inspect(bind).get_table_names():
        return

    op.create_table('report_schedules',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipients', sa.String(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_schedules')
    # ### end Alembic commands ###
