"""add dashboard cache

Revision ID: 4a9f962fdc96
Revises: 9c0942d6082e
Create Date: 2026-07-07 20:48:31.004956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a9f962fdc96'
down_revision: Union[str, Sequence[str], None] = '9c0942d6082e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Idempotent: app startup's create_all() may already have created this table
    on a deploy that raced the migration (same hazard as 9c0942d6082e).
    """
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if "dashboard_cache" in insp.get_table_names():
        return

    op.create_table('dashboard_cache',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('property_key', sa.String(), nullable=False),
    sa.Column('payload', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('last_anomaly_key', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'property_key')
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard_cache')
    # ### end Alembic commands ###
