"""add notification settings

Revision ID: 8a2fd618cc9f
Revises: 2b49f5af03f3
Create Date: 2026-07-12 15:01:10.179376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a2fd618cc9f'
down_revision: Union[str, Sequence[str], None] = '2b49f5af03f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Idempotent: app startup's create_all() may have created the table already
    on a deploy that raced this migration.
    """
    bind = op.get_bind()
    if "notification_settings" in sa.inspect(bind).get_table_names():
        return

    op.create_table('notification_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slack_webhook_url', sa.String(), nullable=True),
    sa.Column('digest_enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('digest_last_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_settings')
    # ### end Alembic commands ###
