"""index integrations user provider

Revision ID: b19ea4c2faeb
Revises: 47e49be32c49
Create Date: 2026-07-13 13:14:06.046657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b19ea4c2faeb'
down_revision: Union[str, Sequence[str], None] = '47e49be32c49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Idempotent: create_all() on a racing deploy may have built the index
    already (it's declared in the model's __table_args__).
    """
    bind = op.get_bind()
    existing = {i["name"] for i in sa.inspect(bind).get_indexes("integrations")}
    if "ix_integrations_user_provider" in existing:
        return
    op.create_index('ix_integrations_user_provider', 'integrations', ['user_id', 'provider'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_integrations_user_provider', table_name='integrations')
    # ### end Alembic commands ###
